In [2]:
import pandas as pd
df = pd.read_excel(r"/content/census_2011.xlsx")
print(df)

     District code                   State name              District name  \
0                1            JAMMU AND KASHMIR                    Kupwara
1                2            JAMMU AND KASHMIR                     Badgam
2                3            JAMMU AND KASHMIR                Leh(Ladakh)
3                4            JAMMU AND KASHMIR                     Kargil
4                5            JAMMU AND KASHMIR                      Punch
..             ...                          ...                        ...
635            636                  PONDICHERRY                       Mahe
636            637                  PONDICHERRY                   Karaikal
637            638  ANDAMAN AND NICOBAR ISLANDS                   Nicobars
638            639  ANDAMAN AND NICOBAR ISLANDS  North  AND Middle Andaman
639            640  ANDAMAN AND NICOBAR ISLANDS              South Andaman

     Population      Male    Female  Literate  Male_Literate  Female_Literate  \
0      870354.0  474190.0  396164.0  439654.0       282823.0         156831.0
1      753745.0       NaN  355704.0  335649.0       207741.0         127908.0
2      133487.0   78971.0   54516.0   93770.0        62834.0          30936.0
3      140802.0       NaN   63017.0       NaN        56301.0          29935.0
4           NaN  251899.0  224936.0  261724.0       163333.0          98391.0
..          ...       ...       ...       ...            ...              ...
635     41816.0   19143.0   22673.0   36470.0        16610.0          19860.0
636    200222.0   97809.0  102413.0  154916.0        79903.0          75013.0
637     36842.0   20727.0       NaN   25332.0        15397.0           9935.0
638    105597.0   54861.0   50736.0   78683.0        43186.0          35497.0
639         NaN  127283.0  110859.0  190266.0       105794.0          84472.0

          SC  ...  Power_Parity_Rs_90000_150000  Power_Parity_Rs_45000_150000  \
0     1048.0  ...                          94.0                         588.0
1        NaN  ...                         126.0                         562.0
2      488.0  ...                          46.0                         122.0
3       18.0  ...                          27.0                         114.0
4      556.0  ...                          78.0                         346.0
..       ...  ...                           ...                           ...
635    144.0  ...                        2316.0                        4309.0
636  35348.0  ...                        1063.0                        2408.0
637      0.0  ...                         685.0                        1895.0
638      0.0  ...                         685.0                        1895.0
639      0.0  ...                        1371.0                        3020.0

     Power_Parity_Rs_150000_240000  Power_Parity_Rs_240000_330000  \
0                             71.0                          101.0
1                             72.0                           89.0
2                             15.0                           22.0
3                             12.0                           18.0
4                             35.0                           50.0
..                             ...                            ...
635                         1370.0                          838.0
636                          665.0                          340.0
637                          212.0                          134.0
638                          212.0                            NaN
639                          649.0                          368.0

     Power_Parity_Rs_150000_330000  Power_Parity_Rs_330000_425000  \
0                            172.0                           74.0
1                            161.0                           96.0
2                              NaN                           20.0
3                             30.0                           19.0
4                             85.0                           59.0
..                             ...                            ...
635                         2208.0                          576.0
636                         1005.0                          246.0
637                          346.0                           70.0
638                          346.0                           70.0
639                         1017.0                          265.0

     Power_Parity_Rs_425000_545000  Power_Parity_Rs_330000_545000  \
0                             10.0                           84.0
1                             28.0                          124.0
2                              NaN                            NaN
3                              3.0                           22.0
4                              8.0                           67.0
..                             ...                            ...
635                          978.0                         1554.0
636                            NaN                          729.0
637                          120.0                          190.0
638                          120.0                          190.0
639                          497.0                          762.0

     Power_Parity_Above_Rs_545000  Total_Power_Parity
0                            15.0              1119.0
1                            18.0              1066.0
2                            17.0               242.0
3                             7.0               214.0
4                            12.0               629.0
..                            ...                 ...
635                        1446.0             10027.0
636                         341.0              4890.0
637                          84.0              3151.0
638                          84.0              3151.0
639                         376.0              5782.0

[640 rows x 118 columns]

In [3]:
new_var = {'State name':'state/UT',
                'District name':'District',
                'Male_Literate':'Literate_Male',
                'Female_Literate':'Literate_Female',
                'Rural_Households':'Households_Rural',
                'Urban_Households':'Households_Urban',
                'Age_Group_0_29':'Youth_and_Adult',
                'Age_Group_30_49':'Middle_Aged',
                'Age_Group_50':'Senior_Citizen',
                'Age not stated':'Age_not_stated'
                }
columns_names=new_var

df_1 = df.rename(columns=columns_names)

print(df_1)

     District code                     state/UT                   District  \
0                1            JAMMU AND KASHMIR                    Kupwara
1                2            JAMMU AND KASHMIR                     Badgam
2                3            JAMMU AND KASHMIR                Leh(Ladakh)
3                4            JAMMU AND KASHMIR                     Kargil
4                5            JAMMU AND KASHMIR                      Punch
..             ...                          ...                        ...
635            636                  PONDICHERRY                       Mahe
636            637                  PONDICHERRY                   Karaikal
637            638  ANDAMAN AND NICOBAR ISLANDS                   Nicobars
638            639  ANDAMAN AND NICOBAR ISLANDS  North  AND Middle Andaman
639            640  ANDAMAN AND NICOBAR ISLANDS              South Andaman

     Population      Male    Female  Literate  Literate_Male  Literate_Female  \
0      870354.0  474190.0  396164.0  439654.0       282823.0         156831.0
1      753745.0       NaN  355704.0  335649.0       207741.0         127908.0
2      133487.0   78971.0   54516.0   93770.0        62834.0          30936.0
3      140802.0       NaN   63017.0       NaN        56301.0          29935.0
4           NaN  251899.0  224936.0  261724.0       163333.0          98391.0
..          ...       ...       ...       ...            ...              ...
635     41816.0   19143.0   22673.0   36470.0        16610.0          19860.0
636    200222.0   97809.0  102413.0  154916.0        79903.0          75013.0
637     36842.0   20727.0       NaN   25332.0        15397.0           9935.0
638    105597.0   54861.0   50736.0   78683.0        43186.0          35497.0
639         NaN  127283.0  110859.0  190266.0       105794.0          84472.0

          SC  ...  Power_Parity_Rs_90000_150000  Power_Parity_Rs_45000_150000  \
0     1048.0  ...                          94.0                         588.0
1        NaN  ...                         126.0                         562.0
2      488.0  ...                          46.0                         122.0
3       18.0  ...                          27.0                         114.0
4      556.0  ...                          78.0                         346.0
..       ...  ...                           ...                           ...
635    144.0  ...                        2316.0                        4309.0
636  35348.0  ...                        1063.0                        2408.0
637      0.0  ...                         685.0                        1895.0
638      0.0  ...                         685.0                        1895.0
639      0.0  ...                        1371.0                        3020.0

     Power_Parity_Rs_150000_240000  Power_Parity_Rs_240000_330000  \
0                             71.0                          101.0
1                             72.0                           89.0
2                             15.0                           22.0
3                             12.0                           18.0
4                             35.0                           50.0
..                             ...                            ...
635                         1370.0                          838.0
636                          665.0                          340.0
637                          212.0                          134.0
638                          212.0                            NaN
639                          649.0                          368.0

     Power_Parity_Rs_150000_330000  Power_Parity_Rs_330000_425000  \
0                            172.0                           74.0
1                            161.0                           96.0
2                              NaN                           20.0
3                             30.0                           19.0
4                             85.0                           59.0
..                             ...                            ...
635                         2208.0                          576.0
636                         1005.0                          246.0
637                          346.0                           70.0
638                          346.0                           70.0
639                         1017.0                          265.0

     Power_Parity_Rs_425000_545000  Power_Parity_Rs_330000_545000  \
0                             10.0                           84.0
1                             28.0                          124.0
2                              NaN                            NaN
3                              3.0                           22.0
4                              8.0                           67.0
..                             ...                            ...
635                          978.0                         1554.0
636                            NaN                          729.0
637                          120.0                          190.0
638                          120.0                          190.0
639                          497.0                          762.0

     Power_Parity_Above_Rs_545000  Total_Power_Parity
0                            15.0              1119.0
1                            18.0              1066.0
2                            17.0               242.0
3                             7.0               214.0
4                            12.0               629.0
..                            ...                 ...
635                        1446.0             10027.0
636                         341.0              4890.0
637                          84.0              3151.0
638                          84.0              3151.0
639                         376.0              5782.0

[640 rows x 118 columns]

In [4]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.10/dist-packages (3.1.3)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.10/dist-packages (from openpyxl) (1.1.0)

In [5]:
!pip install xlsxwriter

Collecting xlsxwriter
  Downloading XlsxWriter-3.2.0-py3-none-any.whl (159 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 159.9/159.9 kB 5.3 MB/s eta 0:00:00
Installing collected packages: xlsxwriter
Successfully installed xlsxwriter-3.2.0

In [6]:
import xlsxwriter
df_1.to_excel('df_2', engine='xlsxwriter')

Task2:  Rename State/UT Names

In [7]:
df_2 = pd.read_excel(r"/content/df_2")

df_2['state/UT'] = df_2['state/UT'].map(str.title)

print(df_2)

df_2.to_excel('df_3', engine='xlsxwriter')

     Unnamed: 0  District code                     state/UT  \
0             0              1            Jammu And Kashmir
1             1              2            Jammu And Kashmir
2             2              3            Jammu And Kashmir
3             3              4            Jammu And Kashmir
4             4              5            Jammu And Kashmir
..          ...            ...                          ...
635         635            636                  Pondicherry
636         636            637                  Pondicherry
637         637            638  Andaman And Nicobar Islands
638         638            639  Andaman And Nicobar Islands
639         639            640  Andaman And Nicobar Islands

                      District  Population      Male    Female  Literate  \
0                      Kupwara    870354.0  474190.0  396164.0  439654.0
1                       Badgam    753745.0       NaN  355704.0  335649.0
2                  Leh(Ladakh)    133487.0   78971.0   54516.0   93770.0
3                       Kargil    140802.0       NaN   63017.0       NaN
4                        Punch         NaN  251899.0  224936.0  261724.0
..                         ...         ...       ...       ...       ...
635                       Mahe     41816.0   19143.0   22673.0   36470.0
636                   Karaikal    200222.0   97809.0  102413.0  154916.0
637                   Nicobars     36842.0   20727.0       NaN   25332.0
638  North  AND Middle Andaman    105597.0   54861.0   50736.0   78683.0
639              South Andaman         NaN  127283.0  110859.0  190266.0

     Literate_Male  Literate_Female  ...  Power_Parity_Rs_90000_150000  \
0         282823.0         156831.0  ...                          94.0
1         207741.0         127908.0  ...                         126.0
2          62834.0          30936.0  ...                          46.0
3          56301.0          29935.0  ...                          27.0
4         163333.0          98391.0  ...                          78.0
..             ...              ...  ...                           ...
635        16610.0          19860.0  ...                        2316.0
636        79903.0          75013.0  ...                        1063.0
637        15397.0           9935.0  ...                         685.0
638        43186.0          35497.0  ...                         685.0
639       105794.0          84472.0  ...                        1371.0

     Power_Parity_Rs_45000_150000  Power_Parity_Rs_150000_240000  \
0                           588.0                           71.0
1                           562.0                           72.0
2                           122.0                           15.0
3                           114.0                           12.0
4                           346.0                           35.0
..                            ...                            ...
635                        4309.0                         1370.0
636                        2408.0                          665.0
637                        1895.0                          212.0
638                        1895.0                          212.0
639                        3020.0                          649.0

     Power_Parity_Rs_240000_330000  Power_Parity_Rs_150000_330000  \
0                            101.0                          172.0
1                             89.0                          161.0
2                             22.0                            NaN
3                             18.0                           30.0
4                             50.0                           85.0
..                             ...                            ...
635                          838.0                         2208.0
636                          340.0                         1005.0
637                          134.0                          346.0
638                            NaN                          346.0
639                          368.0                         1017.0

     Power_Parity_Rs_330000_425000  Power_Parity_Rs_425000_545000  \
0                             74.0                           10.0
1                             96.0                           28.0
2                             20.0                            NaN
3                             19.0                            3.0
4                             59.0                            8.0
..                             ...                            ...
635                          576.0                          978.0
636                          246.0                            NaN
637                           70.0                          120.0
638                           70.0                          120.0
639                          265.0                          497.0

     Power_Parity_Rs_330000_545000  Power_Parity_Above_Rs_545000  \
0                             84.0                          15.0
1                            124.0                          18.0
2                              NaN                          17.0
3                             22.0                           7.0
4                             67.0                          12.0
..                             ...                           ...
635                         1554.0                        1446.0
636                          729.0                         341.0
637                          190.0                          84.0
638                          190.0                          84.0
639                          762.0                         376.0

     Total_Power_Parity
0                1119.0
1                1066.0
2                 242.0
3                 214.0
4                 629.0
..                  ...
635             10027.0
636              4890.0
637              3151.0
638              3151.0
639              5782.0

[640 rows x 119 columns]

In [8]:
import pandas

file = pandas.read_excel("/content/df_3")
for col in file.columns:
    print(col)

Unnamed: 0.1
Unnamed: 0
District code
state/UT
District
Population
Male
Female
Literate
Literate_Male
Literate_Female
SC
Male_SC
Female_SC
ST
Male_ST
Female_ST
Workers
Male_Workers
Female_Workers
Main_Workers
Marginal_Workers
Non_Workers
Cultivator_Workers
Agricultural_Workers
Household_Workers
Other_Workers
Hindus
Muslims
Christians
Sikhs
Buddhists
Jains
Others_Religions
Religion_Not_Stated
LPG_or_PNG_Households
Housholds_with_Electric_Lighting
Households_with_Internet
Households_with_Computer
Households_Rural
Households_Urban
Households
Below_Primary_Education
Primary_Education
Middle_Education
Secondary_Education
Higher_Education
Graduate_Education
Other_Education
Literate_Education
Illiterate_Education
Total_Education
Youth_and_Adult
Middle_Aged
Senior_Citizen
Age_not_stated
Households_with_Bicycle
Households_with_Car_Jeep_Van
Households_with_Radio_Transistor
Households_with_Scooter_Motorcycle_Moped
Households_with_Telephone_Mobile_Phone_Landline_only
Households_with_Telephone_Mobile_Phone_Mobile_only
Households_with_TV_Computer_Laptop_Telephone_mobile_phone_and_Scooter_Car
Households_with_Television
Households_with_Telephone_Mobile_Phone
Households_with_Telephone_Mobile_Phone_Both
Condition_of_occupied_census_houses_Dilapidated_Households
Households_with_separate_kitchen_Cooking_inside_house
Having_bathing_facility_Total_Households
Having_latrine_facility_within_the_premises_Total_Households
Ownership_Owned_Households
Ownership_Rented_Households
Type_of_bathing_facility_Enclosure_without_roof_Households
Type_of_fuel_used_for_cooking_Any_other_Households
Type_of_latrine_facility_Pit_latrine_Households
Type_of_latrine_facility_Other_latrine_Households
Type_of_latrine_facility_Night_soil_disposed_into_open_drain_Households
Type_of_latrine_facility_Flush_pour_flush_latrine_connected_to_other_system_Households
Not_having_bathing_facility_within_the_premises_Total_Households
Not_having_latrine_facility_within_the_premises_Alternative_source_Open_Households
Main_source_of_drinking_water_Un_covered_well_Households
Main_source_of_drinking_water_Handpump_Tubewell_Borewell_Households
Main_source_of_drinking_water_Spring_Households
Main_source_of_drinking_water_River_Canal_Households
Main_source_of_drinking_water_Other_sources_Households
Main_source_of_drinking_water_Other_sources_Spring_River_Canal_Tank_Pond_Lake_Other_sources__Households
Location_of_drinking_water_source_Near_the_premises_Households
Location_of_drinking_water_source_Within_the_premises_Households
Main_source_of_drinking_water_Tank_Pond_Lake_Households
Main_source_of_drinking_water_Tapwater_Households
Main_source_of_drinking_water_Tubewell_Borehole_Households
Household_size_1_person_Households
Household_size_2_persons_Households
Household_size_1_to_2_persons
Household_size_3_persons_Households
Household_size_3_to_5_persons_Households
Household_size_4_persons_Households
Household_size_5_persons_Households
Household_size_6_8_persons_Households
Household_size_9_persons_and_above_Households
Location_of_drinking_water_source_Away_Households
Married_couples_1_Households
Married_couples_2_Households
Married_couples_3_Households
Married_couples_3_or_more_Households
Married_couples_4_Households
Married_couples_5__Households
Married_couples_None_Households
Power_Parity_Less_than_Rs_45000
Power_Parity_Rs_45000_90000
Power_Parity_Rs_90000_150000
Power_Parity_Rs_45000_150000
Power_Parity_Rs_150000_240000
Power_Parity_Rs_240000_330000
Power_Parity_Rs_150000_330000
Power_Parity_Rs_330000_425000
Power_Parity_Rs_425000_545000
Power_Parity_Rs_330000_545000
Power_Parity_Above_Rs_545000
Total_Power_Parity

Task 3: New State/UT formation

In [9]:
import pandas as pd
import openpyxl

# Load the Excel file into a DataFrame
#file_path = '/content/df_3'
df_3 = pd.read_excel('/content/df_3')

# List of districts to update
districts_to_update = ['Adilabad','Nizamabad','Karimnagar','Medak','Hyderabad','Rangareddy',
                       'Mahbubnagar','Nalgonda','Warangal','Khammam']

# Counter to track the number of updates
update_count = 0
max_updates = 10

# Iterate through the DataFrame and update the first 10 occurrences
for index, row in df_3.iterrows():
    if row['District'] in districts_to_update and row['state/UT'] == 'Andhra Pradesh':
        df_3.at[index, 'state/UT'] = 'Telangana'
        update_count += 1
        if update_count >= max_updates:
            break


df_3.to_excel('df_6', engine = 'xlsxwriter')

In [10]:
import pandas as pd
import openpyxl

df_6 = pd.read_excel('/content/df_6')
districts_to_update =['Leh(Ladakh)', 'Kargil']

update_count = 0
max_updates = 2

for index, row in df_6.iterrows():
    if row['District'] in districts_to_update and row['state/UT'] == 'Jammu And Kashmir':
        df_6.at[index, 'state/UT'] = 'Ladakh'
        update_count += 1
        if update_count >= max_updates:
            break


df_6.to_excel('df_P', engine = 'xlsxwriter')

In [11]:
!pip  install tabulate

Requirement already satisfied: tabulate in /usr/local/lib/python3.10/dist-packages (0.9.0)

Task 4: Data cleaning

In [13]:
import pandas as pd
# Load a sample dataset
df_P = pd.read_excel('/content/df_P')


 # Identify the rows with missing values in the "Literate" column
missing_literate = df_P['Literate'].isna()
missing_literate_Male = df_P['Literate_Male'].isna()
missing_literate_Female = df_P['Literate_Female'].isna()

# Calculate the missing values using the sum of "Male-Literate" and "Female-Literate"
df_P.loc[missing_literate, 'Literate'] = df_P['Literate_Male'] + df_P['Literate_Female']
df_P.loc[missing_literate_Male, 'Literate_Male'] = df_P['Literate'] - df_P['Literate_Female']
df_P.loc[missing_literate_Female, 'Literate_Female'] = df_P['Literate'] - df_P['Literate_Male']

#Calculating the missing data for population

missing_Population = df_P['Population'].isna()
missing_Male = df_P['Male'].isna()
missing_Female = df_P['Female'].isna()

df_P.loc[missing_Population, 'Population'] = df_P['Male'] + df_P['Female']
df_P.loc[missing_Male, 'Male'] = df_P['Population'] - df_P['Female']
df_P.loc[missing_Female, 'Female'] = df_P['Population'] - df_P['Male']

#Calculating the missing data for SC_
missing_SC = df_P['SC'].isna()
missing_Male_SC = df_P['Male_SC'].isna()
missing_Female_SC = df_P['Female_SC'].isna()

df_P.loc[missing_SC, 'SC'] = df_P['Male_SC'] + df_P['Female_SC']
df_P.loc[missing_Male_SC, 'Male_SC'] = df_P['SC'] - df_P['Female_SC']
df_P.loc[missing_Female_SC, 'Female_SC'] = df_P['SC'] - df_P['Male_SC']

#Calculating the missing data for ST_
missing_ST = df_P['ST'].isna()
missing_Male_ST = df_P['Male_ST'].isna()
missing_Female_ST = df_P['Female_ST'].isna()

df_P.loc[missing_ST, 'ST'] = df_P['Male_ST'] + df_P['Female_ST']
df_P.loc[missing_Male_ST, 'Male_ST'] = df_P['ST'] - df_P['Female_ST']
df_P.loc[missing_Female_ST, 'Female_ST'] = df_P['ST'] - df_P['Male_ST']

#Calculating the missing data for Workers
missing_Workers = df_P['Workers'].isna()
missing_Male_Workers = df_P['Male_Workers'].isna()
missing_Female_Workers = df_P['Female_Workers'].isna()

df_P.loc[missing_Workers, 'Workers'] = df_P['Male_Workers'] + df_P['Female_Workers']
df_P.loc[missing_Male_Workers, 'Male_Workers'] = df_P['Workers'] - df_P['Female_Workers']
df_P.loc[missing_Female_Workers, 'Female_Workers'] = df_P['Workers'] - df_P['Male_Workers']

# Calculationfg the missing data for Households

missing_Households = df_P['Households'].isna()
missing_Households_Rural = df_P['Households_Rural'].isna()
missing_Households_Urban = df_P['Households_Urban'].isna()

df_P.loc[missing_Households, 'Households'] = df_P['Households_Rural'] + df_P['Households_Urban']
df_P.loc[missing_Households_Rural, 'Households_Rural'] = df_P['Households'] - df_P['Households_Urban']
df_P.loc[missing_Households_Urban, 'Households_Urban'] = df_P['Households'] - df_P['Households_Rural']

# Calculationfg the missing data for Households Youth_and_Adult
# Middle_Aged
# Senior_Citizen

missing_Population = df_P['Population'].isna()
missing_Youth_and_Adult = df_P['Youth_and_Adult'].isna()
missing_Middle_Aged = df_P['Middle_Aged'].isna()
missing_Senior_Citizen = df_P['Senior_Citizen'].isna()

df_P.loc[missing_Youth_and_Adult, 'Youth_and_Adult'] = df_P['Population'] - (df_P['Middle_Aged']+  df_P['Senior_Citizen'])
df_P.loc[missing_Middle_Aged, 'Middle_Aged'] = df_P['Population'] - (df_P['Youth_and_Adult']+  df_P['Senior_Citizen'])
df_P.loc[missing_Senior_Citizen, 'Senior_Citizen'] = df_P['Population'] - (df_P['Middle_Aged']+  df_P['Youth_and_Adult'])

# Calculationfg the missing data
# Main_Workers
# Marginal_Workers
# Non_Workers
# Cultivator_Workers
# Agricultural_Workers
# Household_Workers
# Other_Workers

missing_Main_Workers = df_P['Main_Workers'].isna()
missing_Marginal_Workers = df_P['Marginal_Workers'].isna()
missing_Non_Workers = df_P['Non_Workers'].isna()
missing_Cultivator_Workers = df_P['Cultivator_Workers'].isna()
missing_Agricultural_Workers = df_P['Agricultural_Workers'].isna()
missing_Household_Workers = df_P['Household_Workers'].isna()
missing_Other_Workers = df_P['Other_Workers'].isna()

df_P.loc[missing_Main_Workers,'Main_Workers']= df_P['Population']-(df_P['Marginal_Workers']+ df_P['Non_Workers']  + df_P['Cultivator_Workers']+df_P['Agricultural_Workers'] + df_P['Household_Workers'] +df_P['Other_Workers'])
df_P.loc[missing_Marginal_Workers,'Marginal_Workers'] = df_P['Population']-(df_P['Main_Workers']+ df_P['Non_Workers'] +df_P['Cultivator_Workers']+df_P['Agricultural_Workers'] +df_P['Household_Workers'] +df_P['Other_Workers'])
df_P.loc[missing_Non_Workers,'Non_Workers'] = df_P['Population']-(df_P['Marginal_Workers'] + df_P['Main_Workers'] +df_P['Cultivator_Workers']+df_P['Agricultural_Workers'] +df_P['Household_Workers'] +df_P['Other_Workers'])
df_P.loc[missing_Cultivator_Workers,'Cultivator_Workers'] = df_P['Population']-(df_P['Marginal_Workers']+ df_P['Main_Workers'] +df_P['Non_Workers'] +df_P['Agricultural_Workers'] +df_P['Household_Workers'] +df_P['Other_Workers'])
df_P.loc[missing_Agricultural_Workers,'Agricultural_Workers'] = df_P['Population']-(df_P['Marginal_Workers']+ df_P['Main_Workers'] +df_P['Non_Workers'] +df_P['Cultivator_Workers']+df_P['Household_Workers'] +df_P['Other_Workers'])
df_P.loc[missing_Household_Workers,'Household_Workers'] = df_P['Population']-(df_P['Marginal_Workers']+ df_P['Main_Workers'] +df_P['Non_Workers'] +df_P['Cultivator_Workers']+df_P['Agricultural_Workers'] +df_P['Other_Workers'])
df_P.loc[missing_Other_Workers,'Other_Workers'] = df_P['Population']-( df_P['Main_Workers'] +df_P['Marginal_Workers']+ df_P['Non_Workers'] + df_P['Cultivator_Workers']+df_P['Agricultural_Workers'] + df_P['Household_Workers'] )


# Calculationfg the missing data
# Hindus
# Muslims
# Christians
# Sikhs
# Buddhists
# Jains
# Others_Religions
# Religion_Not_Stated

missing_Hindus = df_P['Hindus'].isna()
missing_Muslims = df_P['Muslims'].isna()
missing_Christians = df_P['Christians'].isna()
missing_Sikhs = df_P['Sikhs'].isna()
missing_Buddhists = df_P['Buddhists'].isna()
missing_Jains = df_P['Jains'].isna()
missing_Others_Religions = df_P['Others_Religions'].isna()
missing_Religion_Not_Stated = df_P['Religion_Not_Stated'].isna()

df_P.loc[missing_Hindus,'Hindus']=df_P['Population']-( df_P['Muslims'] + df_P['Christians'] + df_P['Sikhs'] + df_P['Buddhists'] + df['Jains'] +df_P['Others_Religions'] + df_P['Religion_Not_Stated'])
df_P.loc[missing_Muslims,'Muslims'] = df_P['Population']- (df_P['Hindus'] + df_P['Christians'] + df_P['Sikhs'] + df_P['Buddhists'] + df['Jains'] +df_P['Others_Religions'] + df_P['Religion_Not_Stated'])
df_P.loc[missing_Christians,'Christians'] = df_P['Population']-(df_P['Hindus'] + df_P['Muslims'] + df_P['Sikhs'] + df_P['Buddhists'] + df['Jains'] +df_P['Others_Religions'] + df_P['Religion_Not_Stated'])
df_P.loc[missing_Sikhs,'Sikhs'] = df_P['Population']- (df_P['Hindus'] + df_P['Muslims'] + df_P['Christians'] + df_P['Buddhists'] + df['Jains'] +df_P['Others_Religions'] + df_P['Religion_Not_Stated'])
df_P.loc[missing_Buddhists,'Buddhists'] = df_P['Population']- (df_P['Hindus'] + df_P['Muslims'] + df_P['Christians'] +df_P['Sikhs'] + df['Jains'] +df_P['Others_Religions'] + df_P['Religion_Not_Stated'])
df_P.loc[missing_Jains,'Jains'] = df_P['Population']- (df_P['Hindus'] + df_P['Muslims'] + df_P['Christians'] +df_P['Sikhs'] +df_P['Buddhists']  +df_P['Others_Religions'] + df_P['Religion_Not_Stated'])
df_P.loc[missing_Others_Religions,'Others_Religions'] = df_P['Population']-(df_P['Hindus'] + df_P['Muslims'] + df_P['Christians'] +df_P['Sikhs'] +df_P['Buddhists']+ df['Jains'] + df_P['Religion_Not_Stated'])
df_P.loc[missing_Religion_Not_Stated,'Religion_Not_Stated'] = df_P['Population']- (df_P['Hindus'] + df_P['Muslims'] + df_P['Christians'] +df_P['Sikhs'] +df_P['Buddhists'] + df['Jains'] +df_P['Others_Religions'])




df_P.to_excel('df_R2', engine = 'xlsxwriter')

In [14]:
import pandas as pd
df_R2 = pd.read_excel('/content/df_R2')

# Household_size_1_person_Households
# Household_size_2_persons_Households
# Household_size_1_to_2_persons
# Household_size_3_persons_Households
# Household_size_3_to_5_persons_Households
# Household_size_4_persons_Households
# Household_size_5_persons_Households


missing_Household_size_1_person_Households =df_R2['Household_size_1_person_Households'].isna()
missing_Household_size_2_persons_Households =df_R2['Household_size_2_persons_Households'].isna()
missing_Household_size_1_to_2_persons = df_R2['Household_size_1_to_2_persons'].isna()
missing_Household_size_3_persons_Households =df_R2['Household_size_3_persons_Households'].isna()
missing_Household_size_3_to_5_persons_Households =df_R2['Household_size_3_to_5_persons_Households'].isna()
missing_Household_size_4_persons_Households =df_R2['Household_size_4_persons_Households'].isna()
missing_Household_size_5_persons_Households = df_R2['Household_size_5_persons_Households'].isna()


df_R2.loc[missing_Household_size_1_person_Households ,'Household_size_1_person_Households'] = df_R2['Household_size_1_to_2_persons'] - df_R2['Household_size_2_persons_Households']
df_R2.loc[missing_Household_size_2_persons_Households,'Household_size_2_persons_Households'] = df_R2['Household_size_1_to_2_persons'] - df_R2['Household_size_1_person_Households']
df_R2.loc[missing_Household_size_1_to_2_persons,'Household_size_1_to_2_persons'] = df_R2['Household_size_1_person_Households'] + df_R2['Household_size_2_persons_Households']
df_R2.loc[missing_Household_size_3_to_5_persons_Households,'Household_size_3_to_5_persons_Households'] = (df_R2['Household_size_3_persons_Households'] + df_R2['Household_size_4_persons_Households'] + df_R2['Household_size_5_persons_Households'])
df_R2.loc[missing_Household_size_3_persons_Households,'Household_size_3_persons_Households'] = df_R2['Household_size_3_to_5_persons_Households'] - (df_R2['Household_size_4_persons_Households'] + df_R2['Household_size_5_persons_Households'] )
df_R2.loc[missing_Household_size_4_persons_Households,'Household_size_4_persons_Households'] = df_R2['Household_size_3_to_5_persons_Households'] - (df_R2['Household_size_3_persons_Households'] + df_R2['Household_size_5_persons_Households'] )
df_R2.loc[missing_Household_size_5_persons_Households,'Household_size_5_persons_Households'] = df_R2['Household_size_3_to_5_persons_Households'] - (df_R2['Household_size_3_persons_Households'] + df_R2['Household_size_4_persons_Households'] )

# Total literate edducation
missing_Below_Primary_Education = df_R2['Below_Primary_Education'].isna()
missing_Primary_Education = df_R2['Primary_Education'].isna()
missing_Middle_Education = df_R2['Middle_Education'].isna()
missing_Secondary_Education = df_R2['Secondary_Education'].isna()
missing_Higher_Education = df_R2['Higher_Education'].isna()
missing_Graduate_Education = df_R2['Graduate_Education'].isna()
missing_Other_Education = df_R2['Other_Education'].isna()
missing_Literate_Education = df_R2['Literate_Education'].isna()

df_R2.loc[missing_Literate_Education,'Literate_Education'] = df_R2['Below_Primary_Education'] + df_R2['Primary_Education'] + df_R2['Middle_Education'] + df_R2['Secondary_Education'] + df_R2['Higher_Education'] + df_R2['Graduate_Education'] +  df_R2['Other_Education']
df_R2.loc[missing_Below_Primary_Education,'Below_Primary_Education'] =  df_R2['Literate_Education'] -(df_R2['Primary_Education'] +df_R2['Middle_Education'] + df_R2['Secondary_Education'] + df_R2['Higher_Education'] + df_R2['Graduate_Education'] +  df_R2['Other_Education'])
df_R2.loc[missing_Primary_Education,'Primary_Education']  = df_R2['Literate_Education'] -(df_R2['Below_Primary_Education'] +df_R2['Middle_Education'] + df_R2['Secondary_Education'] + df_R2['Higher_Education'] + df_R2['Graduate_Education'] +  df_R2['Other_Education'])
df_R2.loc[missing_Middle_Education,'Middle_Education'] =  df_R2['Literate_Education'] -  (df_R2['Below_Primary_Education'] + df_R2['Primary_Education'] + df_R2['Secondary_Education'] + df_R2['Higher_Education'] + df_R2['Graduate_Education'] +  df_R2['Other_Education'] )
df_R2.loc[missing_Secondary_Education,'Secondary_Education'] =  df_R2['Literate_Education'] - (df_R2['Below_Primary_Education'] + df_R2['Primary_Education'] +df_R2['Middle_Education'] + df_R2['Higher_Education'] + df_R2['Graduate_Education'] +  df_R2['Other_Education'])
df_R2.loc[missing_Higher_Education,'Higher_Education'] =  df_R2['Literate_Education'] -(df_R2['Below_Primary_Education'] + df_R2['Primary_Education'] +df_R2['Middle_Education'] + df_R2['Secondary_Education'] + df_R2['Graduate_Education'] +  df_R2['Other_Education'])
df_R2.loc[missing_Graduate_Education,'Graduate_Education'] =  df_R2['Literate_Education'] -(df_R2['Below_Primary_Education'] + df_R2['Primary_Education'] +df_R2['Middle_Education'] + df_R2['Secondary_Education'] + df_R2['Higher_Education']  +  df_R2['Other_Education'])
df_R2.loc[missing_Other_Education,'Other_Education']  = df_R2['Literate_Education'] -(df_R2['Below_Primary_Education'] + df_R2['Primary_Education'] +df_R2['Middle_Education'] + df_R2['Secondary_Education'] + df_R2['Higher_Education'] + df_R2['Graduate_Education'])

#



df_R2.to_excel('df_H', engine = 'xlsxwriter')

Task 4. evaluate_missing_data before and after data cleaning

In [21]:
import pandas as pd
from prettytable import PrettyTable

def calculate_missing_data_percentage(df):
    total_cells = df.size
    missing_cells = df.isnull().sum().sum()
    missing_percentage = (missing_cells / total_cells) * 100
    return missing_percentage

def calculate_column_missing_percentage(df):
    missing_percentage_per_column = df.isnull().sum() / len(df) * 100
    return missing_percentage_per_column

def evaluate_missing_data(file_path1, file_path2):
    # Read CSV files into DataFrames
    df1 = pd.read_excel('/content/df_P')
    df2 = pd.read_excel('/content/df_H')

    # Calculate overall missing data percentage
    missing_percentage_before_data_Cleaning = calculate_missing_data_percentage(df1)
    missing_percentage_after_data_Cleaning = calculate_missing_data_percentage(df2)

    # Calculate missing data percentage per column
    column_missing_percentage_before_data_Cleaning = calculate_column_missing_percentage(df1)
    column_missing_percentage_after_data_Cleaning = calculate_column_missing_percentage(df2)

    # Create tables for displaying the results
    overall_table = PrettyTable()
    overall_table.field_names = ["File", "Overall Missing Data Percentage"]
    overall_table.add_row([file_path1, f"{missing_percentage_before_data_Cleaning:.2f}%"])
    overall_table.add_row([file_path2, f"{ missing_percentage_after_data_Cleaning:.2f}%"])

    column_table1 = PrettyTable()
    column_table1.field_names = ["Column", "Missing Data Percentage"]
    for column, percentage in column_missing_percentage_before_data_Cleaning.items():
        column_table1.add_row([column, f"{percentage:.2f}%"])

    column_table2 = PrettyTable()
    column_table2.field_names = ["Column", "Missing Data Percentage"]
    for column, percentage in column_missing_percentage_after_data_Cleaning.items():
        column_table2.add_row([column, f"{percentage:.2f}%"])

    print(f"Overall Missing Data Percentage:\n{overall_table}")
    print(f"\nMissing Data Percentage Per Column for  before data cleaning:\n{column_table1}")
    print(f"\nMissing Data Percentage Per Column for after data cleaning:\n{column_table2}")

# Paths to the CSV files
file_path1 = 'Before_cleaning'
file_path2 = 'After_Cleaning' # Replace with the path to your second CSV file

# Evaluate missing data
evaluate_missing_data(file_path1, file_path2)

#  # Create DataFrame for results
# results = pd.DataFrame({
#         'Column': df.columns,
#         'Missing Percentage Before Cleaning': column_table1.values,
#         'Missing Percentage After Cleaning': column_table2.values
#     })
# # overall_results = pd.DataFrame({
# #         'Overall Missing Percentage': [  missing_percentage_before_data_Cleaning,missing_percentage_after_data_Cleaning ],
# #         'Description': ['Before Cleaning', 'After Cleaning']
# #     })

#     # Write the results to CSV files
# results.to_csv('missing_data_percentage_per_column.csv', index=False)
# overall_results.to_csv('overall_missing_data_percentage.csv', index=False)

# print("Missing data percentage before and after cleaning has been saved to CSV files.")

Overall Missing Data Percentage:
+-----------------+---------------------------------+
|       File      | Overall Missing Data Percentage |
+-----------------+---------------------------------+
| Before_cleaning |              4.64%              |
|  After_Cleaning |              2.92%              |
+-----------------+---------------------------------+

Missing Data Percentage Per Column for  before data cleaning:
+---------------------------------------------------------------------------------------------------------+-------------------------+
|                                                  Column                                                 | Missing Data Percentage |
+---------------------------------------------------------------------------------------------------------+-------------------------+
|                                               Unnamed: 0.3                                              |          0.00%          |
|                                               Unnamed: 0.2                                              |          0.00%          |
|                                               Unnamed: 0.1                                              |          0.00%          |
|                                                Unnamed: 0                                               |          0.00%          |
|                                              District code                                              |          0.00%          |
|                                                 state/UT                                                |          0.00%          |
|                                                 District                                                |          0.00%          |
|                                                Population                                               |          4.69%          |
|                                                   Male                                                  |          4.69%          |
|                                                  Female                                                 |          5.16%          |
|                                                 Literate                                                |          5.62%          |
|                                              Literate_Male                                              |          4.84%          |
|                                             Literate_Female                                             |          4.22%          |
|                                                    SC                                                   |          5.47%          |
|                                                 Male_SC                                                 |          3.59%          |
|                                                Female_SC                                                |          5.00%          |
|                                                    ST                                                   |          4.53%          |
|                                                 Male_ST                                                 |          4.84%          |
|                                                Female_ST                                                |          4.84%          |
|                                                 Workers                                                 |          3.59%          |
|                                               Male_Workers                                              |          3.44%          |
|                                              Female_Workers                                             |          2.97%          |
|                                               Main_Workers                                              |          4.38%          |
|                                             Marginal_Workers                                            |          6.09%          |
|                                               Non_Workers                                               |          5.62%          |
|                                            Cultivator_Workers                                           |          4.53%          |
|                                           Agricultural_Workers                                          |          4.22%          |
|                                            Household_Workers                                            |          4.38%          |
|                                              Other_Workers                                              |          4.38%          |
|                                                  Hindus                                                 |          4.22%          |
|                                                 Muslims                                                 |          5.78%          |
|                                                Christians                                               |          4.69%          |
|                                                  Sikhs                                                  |          4.53%          |
|                                                Buddhists                                                |          4.06%          |
|                                                  Jains                                                  |          6.56%          |
|                                             Others_Religions                                            |          4.69%          |
|                                           Religion_Not_Stated                                           |          5.47%          |
|                                          LPG_or_PNG_Households                                          |          5.78%          |
|                                     Housholds_with_Electric_Lighting                                    |          6.41%          |
|                                         Households_with_Internet                                        |          3.59%          |
|                                         Households_with_Computer                                        |          4.22%          |
|                                             Households_Rural                                            |          6.56%          |
|                                             Households_Urban                                            |          5.16%          |
|                                                Households                                               |          5.00%          |
|                                         Below_Primary_Education                                         |          5.31%          |
|                                            Primary_Education                                            |          6.41%          |
|                                             Middle_Education                                            |          5.94%          |
|                                           Secondary_Education                                           |          5.78%          |
|                                             Higher_Education                                            |          3.28%          |
|                                            Graduate_Education                                           |          4.69%          |
|                                             Other_Education                                             |          4.06%          |
|                                            Literate_Education                                           |          5.78%          |
|                                           Illiterate_Education                                          |          4.53%          |
|                                             Total_Education                                             |          6.41%          |
|                                             Youth_and_Adult                                             |          4.84%          |
|                                               Middle_Aged                                               |          4.69%          |
|                                              Senior_Citizen                                             |          4.84%          |
|                                              Age_not_stated                                             |          5.47%          |
|                                         Households_with_Bicycle                                         |          4.06%          |
|                                       Households_with_Car_Jeep_Van                                      |          4.22%          |
|                                     Households_with_Radio_Transistor                                    |          4.53%          |
|                                 Households_with_Scooter_Motorcycle_Moped                                |          6.41%          |
|                           Households_with_Telephone_Mobile_Phone_Landline_only                          |          4.69%          |
|                            Households_with_Telephone_Mobile_Phone_Mobile_only                           |          4.38%          |
|                Households_with_TV_Computer_Laptop_Telephone_mobile_phone_and_Scooter_Car                |          5.16%          |
|                                        Households_with_Television                                       |          5.16%          |
|                                  Households_with_Telephone_Mobile_Phone                                 |          5.00%          |
|                               Households_with_Telephone_Mobile_Phone_Both                               |          5.31%          |
|                        Condition_of_occupied_census_houses_Dilapidated_Households                       |          5.16%          |
|                          Households_with_separate_kitchen_Cooking_inside_house                          |          4.53%          |
|                                 Having_bathing_facility_Total_Households                                |          4.06%          |
|                       Having_latrine_facility_within_the_premises_Total_Households                      |          4.22%          |
|                                        Ownership_Owned_Households                                       |          5.31%          |
|                                       Ownership_Rented_Households                                       |          5.00%          |
|                        Type_of_bathing_facility_Enclosure_without_roof_Households                       |          5.94%          |
|                            Type_of_fuel_used_for_cooking_Any_other_Households                           |          5.94%          |
|                             Type_of_latrine_facility_Pit_latrine_Households                             |          5.47%          |
|                            Type_of_latrine_facility_Other_latrine_Households                            |          4.38%          |
|                 Type_of_latrine_facility_Night_soil_disposed_into_open_drain_Households                 |          3.75%          |
|          Type_of_latrine_facility_Flush_pour_flush_latrine_connected_to_other_system_Households         |          4.22%          |
|                     Not_having_bathing_facility_within_the_premises_Total_Households                    |          5.00%          |
|            Not_having_latrine_facility_within_the_premises_Alternative_source_Open_Households           |          6.72%          |
|                         Main_source_of_drinking_water_Un_covered_well_Households                        |          6.41%          |
|                   Main_source_of_drinking_water_Handpump_Tubewell_Borewell_Households                   |          4.84%          |
|                             Main_source_of_drinking_water_Spring_Households                             |          5.00%          |
|                           Main_source_of_drinking_water_River_Canal_Households                          |          6.72%          |
|                          Main_source_of_drinking_water_Other_sources_Households                         |          4.69%          |
| Main_source_of_drinking_water_Other_sources_Spring_River_Canal_Tank_Pond_Lake_Other_sources__Households |          3.44%          |
|                      Location_of_drinking_water_source_Near_the_premises_Households                     |          4.69%          |
|                     Location_of_drinking_water_source_Within_the_premises_Households                    |          4.38%          |
|                         Main_source_of_drinking_water_Tank_Pond_Lake_Households                         |          5.62%          |
|                            Main_source_of_drinking_water_Tapwater_Households                            |          6.56%          |
|                        Main_source_of_drinking_water_Tubewell_Borehole_Households                       |          4.22%          |
|                                    Household_size_1_person_Households                                   |          4.38%          |
|                                   Household_size_2_persons_Households                                   |          5.31%          |
|                                      Household_size_1_to_2_persons                                      |          5.31%          |
|                                   Household_size_3_persons_Households                                   |          4.38%          |
|                                 Household_size_3_to_5_persons_Households                                |          4.53%          |
|                                   Household_size_4_persons_Households                                   |          6.56%          |
|                                   Household_size_5_persons_Households                                   |          4.84%          |
|                                  Household_size_6_8_persons_Households                                  |          5.62%          |
|                              Household_size_9_persons_and_above_Households                              |          4.69%          |
|                            Location_of_drinking_water_source_Away_Households                            |          4.38%          |
|                                       Married_couples_1_Households                                      |          4.69%          |
|                                       Married_couples_2_Households                                      |          4.53%          |
|                                       Married_couples_3_Households                                      |          5.47%          |
|                                   Married_couples_3_or_more_Households                                  |          5.00%          |
|                                       Married_couples_4_Households                                      |          4.06%          |
|                                      Married_couples_5__Households                                      |          4.53%          |
|                                     Married_couples_None_Households                                     |          4.69%          |
|                                     Power_Parity_Less_than_Rs_45000                                     |          4.53%          |
|                                       Power_Parity_Rs_45000_90000                                       |          6.72%          |
|                                       Power_Parity_Rs_90000_150000                                      |          5.16%          |
|                                       Power_Parity_Rs_45000_150000                                      |          4.69%          |
|                                      Power_Parity_Rs_150000_240000                                      |          4.53%          |
|                                      Power_Parity_Rs_240000_330000                                      |          5.47%          |
|                                      Power_Parity_Rs_150000_330000                                      |          3.75%          |
|                                      Power_Parity_Rs_330000_425000                                      |          5.16%          |
|                                      Power_Parity_Rs_425000_545000                                      |          4.69%          |
|                                      Power_Parity_Rs_330000_545000                                      |          3.59%          |
|                                       Power_Parity_Above_Rs_545000                                      |          4.69%          |
|                                            Total_Power_Parity                                           |          5.00%          |
+---------------------------------------------------------------------------------------------------------+-------------------------+

Missing Data Percentage Per Column for after data cleaning:
+---------------------------------------------------------------------------------------------------------+-------------------------+
|                                                  Column                                                 | Missing Data Percentage |
+---------------------------------------------------------------------------------------------------------+-------------------------+
|                                               Unnamed: 0.5                                              |          0.00%          |
|                                               Unnamed: 0.4                                              |          0.00%          |
|                                               Unnamed: 0.3                                              |          0.00%          |
|                                               Unnamed: 0.2                                              |          0.00%          |
|                                               Unnamed: 0.1                                              |          0.00%          |
|                                                Unnamed: 0                                               |          0.00%          |
|                                              District code                                              |          0.00%          |
|                                                 state/UT                                                |          0.00%          |
|                                                 District                                                |          0.00%          |
|                                                Population                                               |          0.16%          |
|                                                   Male                                                  |          0.16%          |
|                                                  Female                                                 |          0.00%          |
|                                                 Literate                                                |          0.31%          |
|                                              Literate_Male                                              |          0.31%          |
|                                             Literate_Female                                             |          0.31%          |
|                                                    SC                                                   |          0.62%          |

filled the remaining empty cell with zero

In [16]:
import pandas as pd

df_H = pd.read_excel('/content/df_H')

df_H.fillna(0, inplace=True)

df_H.to_excel('df_G', engine = 'xlsxwriter')

Task 5: saving the dataframe in Mongodb

In [1]:
!python -m pip install "pymongo[srv]"

Collecting pymongo[srv]
  Downloading pymongo-4.7.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (669 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 669.1/669.1 kB 6.1 MB/s eta 0:00:00
Collecting dnspython<3.0.0,>=1.16.0 (from pymongo[srv])
  Downloading dnspython-2.6.1-py3-none-any.whl (307 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 307.7/307.7 kB 14.8 MB/s eta 0:00:00
Installing collected packages: dnspython, pymongo
Successfully installed dnspython-2.6.1 pymongo-4.7.3

In [2]:
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

uri = "mongodb+srv://indhumathi111666:Catrabrave@cluster0.wqt8xys.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [17]:
import pandas as pd
from pymongo import MongoClient

# Function to insert CSV data into MongoDB
def insert_csv_to_mongodb(csv_file, db_name, collection_name):
    # Step 1: Load CSV data into a pandas DataFrame
    df = pd.read_csv('/content/df_Census.csv')

    # Step 2: Convert DataFrame to a list of dictionaries
    data = df.to_dict(orient='records')

    # Step 3: Connect to MongoDB server
    client = MongoClient( "mongodb+srv://indhumathi111666:Catrabrave@cluster0.wqt8xys.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0")  # Update the URI if your MongoDB server is hosted elsewhere

    # Step 4: Create a database
    db = client[db_name]

    # Step 5: Create a collection
    collection = db[collection_name]

    # Step 6: Insert data into the collection
    insert_result = collection.insert_many(data)
    print(f"Inserted {len(insert_result.inserted_ids)} documents into the collection.")

# Parameters
csv_file = '/content/df_Census.csv'  # Update with the path to your CSV file
db_name = 'test'  # Replace with your desired database name
collection_name = 'Census'  # Replace with your desired collection name

# Call the function
insert_csv_to_mongodb(csv_file, db_name, collection_name)

Inserted 640 documents into the collection.

In [3]:
import pandas as pd
from pymongo import MongoClient
#client = MongoClient()

db = client['test']
collection = db['Census']

# Fetch the data
data = list(collection.find())

# Convert to DataFrame
df_Census = pd.DataFrame(data)

# Optionally, drop the MongoDB '_id' field if it's not needed
if '_id' in df_Census.columns:
    df_Census.drop(columns=['_id'], inplace=True)

output_file_path = '/content/df_Census.csv'  # Replace with your desired output file path
df_Census.to_csv(output_file_path, index=False)

print(df_Census )

     Unnamed: 0.1  Unnamed: 0  District code                     state/UT  \
0               0           0              1            Jammu And Kashmir
1               1           1              2            Jammu And Kashmir
2               2           2              3                       Ladakh
3               3           3              4                       Ladakh
4               4           4              5            Jammu And Kashmir
..            ...         ...            ...                          ...
635           635         635            636                  Pondicherry
636           636         636            637                  Pondicherry
637           637         637            638  Andaman And Nicobar Islands
638           638         638            639  Andaman And Nicobar Islands
639           639         639            640  Andaman And Nicobar Islands

                      District  Population    Male  Female  Literate  \
0                      Kupwara      870354  474190  396164    439654
1                       Badgam      753745  398041  355704    335649
2                  Leh(Ladakh)      133487   78971   54516     93770
3                       Kargil      140802   77785   63017     86236
4                        Punch      476835  251899  224936    261724
..                         ...         ...     ...     ...       ...
635                       Mahe       41816   19143   22673     36470
636                   Karaikal      200222   97809  102413    154916
637                   Nicobars       36842   20727   16115     25332
638  North  AND Middle Andaman      105597   54861   50736     78683
639              South Andaman      238142  127283  110859    190266

     Literate_Male  ...  Power_Parity_Rs_90000_150000  \
0           282823  ...                            94
1           207741  ...                           126
2            62834  ...                            46
3            56301  ...                            27
4           163333  ...                            78
..             ...  ...                           ...
635          16610  ...                          2316
636          79903  ...                          1063
637          15397  ...                           685
638          43186  ...                           685
639         105794  ...                          1371

     Power_Parity_Rs_45000_150000  Power_Parity_Rs_150000_240000  \
0                             588                             71
1                             562                             72
2                             122                             15
3                             114                             12
4                             346                             35
..                            ...                            ...
635                          4309                           1370
636                          2408                            665
637                          1895                            212
638                          1895                            212
639                          3020                            649

     Power_Parity_Rs_240000_330000  Power_Parity_Rs_150000_330000  \
0                              101                            172
1                               89                            161
2                               22                              0
3                               18                             30
4                               50                             85
..                             ...                            ...
635                            838                           2208
636                            340                           1005
637                            134                            346
638                              0                            346
639                            368                           1017

     Power_Parity_Rs_330000_425000  Power_Parity_Rs_425000_545000  \
0                               74                             10
1                               96                             28
2                               20                              0
3                               19                              3
4                               59                              8
..                             ...                            ...
635                            576                            978
636                            246                              0
637                             70                            120
638                             70                            120
639                            265                            497

     Power_Parity_Rs_330000_545000  Power_Parity_Above_Rs_545000  \
0                               84                            15
1                              124                            18
2                                0                            17
3                               22                             7
4                               67                            12
..                             ...                           ...
635                           1554                          1446
636                            729                           341
637                            190                            84
638                            190                            84
639                            762                           376

     Total_Power_Parity
0                  1119
1                  1066
2                   242
3                   214
4                   629
..                  ...
635               10027
636                4890
637                3151
638                3151
639                5782

[640 rows x 120 columns]

In [16]:
from pymongo import MongoClient

def rename_columns_in_mongodb(test , Census):


    # Select the database
    db = client['test']

    # Select the collection
    collection = db['Census']

    # Define the renaming mappings
    rename_mappings = {
        "District code": "District_code",
        "State_UT": "state_UT",
        "Households_with_TV_Computer_Laptop_Telephone_mobile_phone_and_Scooter_Car": "Households_TV_Computer_Laptop_Telephone_mobile_phone_Scooter_Car",
        "Type_of_latrine_facility_Night_soil_disposed_into_open_drain_Households": "Type_of_latrine_facility_Night_soil_disposed_into_open_drain",
        "Type_of_latrine_facility_Flush_pour_flush_latrine_connected_to_other_system_Households": "Type_of_latrine_Flush_pour_connected_to_other_system_Households",
        "Not_having_latrine_facility_within_the_premises_Alternative_source_Open_Households": "Not_having_latrine_within_premises_Other_source_Open_Households",
        "Main_source_of_drinking_water_Handpump_Tubewell_Borewell_Households": "Source_of_drinking_water_Handpump_Tubewell_Borewell_Households",
        "Main_source_of_drinking_water_Other_sources_Spring_River_Canal_Tank_Pond_Lake_Other_sources__Households": "Drinking_water_Spring_River_Canal_Tank_Pond_Lake_Other_Household"
    }

    # Rename fields
    for old_name, new_name in rename_mappings.items():
        result = collection.update_many(
            {old_name: {"$exists": True}},  # Condition to check if the old field exists
            {"$rename": {old_name: new_name}}  # Rename operation
        )

        print(f"Matched {result.matched_count} documents and modified {result.modified_count} documents.")
        print(f"Field '{old_name}' has been renamed to '{new_name}'.")

# Example usage
rename_columns_in_mongodb("test", "Census")

Matched 0 documents and modified 0 documents.
Field 'District code' has been renamed to 'District_code'.
Matched 0 documents and modified 0 documents.
Field 'State_UT' has been renamed to 'state_UT'.
Matched 0 documents and modified 0 documents.
Field 'Households_with_TV_Computer_Laptop_Telephone_mobile_phone_and_Scooter_Car' has been renamed to 'Households_TV_Computer_Laptop_Telephone_mobile_phone_Scooter_Car'.
Matched 0 documents and modified 0 documents.
Field 'Type_of_latrine_facility_Night_soil_disposed_into_open_drain_Households' has been renamed to 'Type_of_latrine_facility_Night_soil_disposed_into_open_drain'.
Matched 0 documents and modified 0 documents.
Field 'Type_of_latrine_facility_Flush_pour_flush_latrine_connected_to_other_system_Households' has been renamed to 'Type_of_latrine_Flush_pour_connected_to_other_system_Households'.
Matched 0 documents and modified 0 documents.
Field 'Not_having_latrine_facility_within_the_premises_Alternative_source_Open_Households' has been renamed to 'Not_having_latrine_within_premises_Other_source_Open_Households'.
Matched 0 documents and modified 0 documents.
Field 'Main_source_of_drinking_water_Handpump_Tubewell_Borewell_Households' has been renamed to 'Source_of_drinking_water_Handpump_Tubewell_Borewell_Households'.
Matched 0 documents and modified 0 documents.
Field 'Main_source_of_drinking_water_Other_sources_Spring_River_Canal_Tank_Pond_Lake_Other_sources__Households' has been renamed to 'Drinking_water_Spring_River_Canal_Tank_Pond_Lake_Other_Household'.

In [19]:
import pandas as pd
from pymongo import MongoClient
#client = MongoClient()

db = client['test']
collection = db['Census']

# Fetch the data
data = list(collection.find())

# Convert to DataFrame
Census_df = pd.DataFrame(data)

# Optionally, drop the MongoDB '_id' field if it's not needed
if '_id' in df_Census.columns:
    df_Census.drop(columns=['_id'], inplace=True)

output_file_path = '/content/Census_df.csv'  # Replace with your desired output file path
Census_df.to_csv(output_file_path, index=False)

print(Census_df )

                          _id  Unnamed: 0.1  Unnamed: 0  \
0    66674bcdfde2224ff26faa12             0           0
1    66674bcdfde2224ff26faa13             1           1
2    66674bcdfde2224ff26faa14             2           2
3    66674bcdfde2224ff26faa15             3           3
4    66674bcdfde2224ff26faa16             4           4
..                        ...           ...         ...
635  66674bcdfde2224ff26fac8d           635         635
636  66674bcdfde2224ff26fac8e           636         636
637  66674bcdfde2224ff26fac8f           637         637
638  66674bcdfde2224ff26fac90           638         638
639  66674bcdfde2224ff26fac91           639         639

                      District  Population    Male  Female  Literate  \
0                      Kupwara      870354  474190  396164    439654
1                       Badgam      753745  398041  355704    335649
2                  Leh(Ladakh)      133487   78971   54516     93770
3                       Kargil      140802   77785   63017     86236
4                        Punch      476835  251899  224936    261724
..                         ...         ...     ...     ...       ...
635                       Mahe       41816   19143   22673     36470
636                   Karaikal      200222   97809  102413    154916
637                   Nicobars       36842   20727   16115     25332
638  North  AND Middle Andaman      105597   54861   50736     78683
639              South Andaman      238142  127283  110859    190266

     Literate_Male  Literate_Female  ...  Power_Parity_Above_Rs_545000  \
0           282823           156831  ...                            15
1           207741           127908  ...                            18
2            62834            30936  ...                            17
3            56301            29935  ...                             7
4           163333            98391  ...                            12
..             ...              ...  ...                           ...
635          16610            19860  ...                          1446
636          79903            75013  ...                           341
637          15397             9935  ...                            84
638          43186            35497  ...                            84
639         105794            84472  ...                           376

     Total_Power_Parity  District_code  \
0                  1119              1
1                  1066              2
2                   242              3
3                   214              4
4                   629              5
..                  ...            ...
635               10027            636
636                4890            637
637                3151            638
638                3151            639
639                5782            640

     Households_TV_Computer_Laptop_Telephone_mobile_phone_Scooter_Car  \
0                                                  495
1                                                 1655
2                                                  971
3                                                  249
4                                                  276
..                                                 ...
635                                                817
636                                               3646
637                                                 78
638                                                561
639                                               4460

     Type_of_latrine_facility_Night_soil_disposed_into_open_drain  \
0                                                 2269
1                                                 1779
2                                                   53
3                                                    0
4                                                  338
..                                                 ...
635                                                  6
636                                                 39
637                                                  2
638                                                116
639                                                 33

     Type_of_latrine_Flush_pour_connected_to_other_system_Households  \
0                                                10919
1                                                 9208
2                                                  695
3                                                 9610
4                                                 1174
..                                                 ...
635                                                 52
636                                                201
637                                                111
638                                               1044
639                                                619

     Not_having_latrine_within_premises_Other_source_Open_Households  \
0                                                44123
1                                                10642
2                                                 1781
3                                                  482
4                                                70470
..                                                 ...
635                                                 46
636                                              18107
637                                               1823
638                                              13375
639                                              10443

     Source_of_drinking_water_Handpump_Tubewell_Borewell_Households  \
0                                                 5030
1                                                 9864
2                                                 5991
3                                                 3289
4                                                 4036
..                                                 ...
635                                                147
636                                                  0
637                                                  5
638                                                145
639                                                  0

     Drinking_water_Spring_River_Canal_Tank_Pond_Lake_Other_Household   \
0                                                34882
1                                                14705
2                                                 8355
3                                                 4068
4                                                19458
..                                                 ...
635                                                 10
636                                                290
637                                               1456
638                                               3794
639                                               1413

                        state_UT
0              Jammu And Kashmir
1              Jammu And Kashmir
2                         Ladakh
3                         Ladakh
4              Jammu And Kashmir
..                           ...
635                  Pondicherry
636                  Pondicherry
637  Andaman And Nicobar Islands
638  Andaman And Nicobar Islands
639  Andaman And Nicobar Islands

[640 rows x 121 columns]

In [18]:
from pymongo import MongoClient
    # Select the database
db = client['test']

    # Select the collection
collection = db['Census']

for col in Census_df.columns:
    print(col)

_id
Unnamed: 0.1
Unnamed: 0
District
Population
Male
Female
Literate
Literate_Male
Literate_Female
SC
Male_SC
Female_SC
ST
Male_ST
Female_ST
Workers
Male_Workers
Female_Workers
Main_Workers
Marginal_Workers
Non_Workers
Cultivator_Workers
Agricultural_Workers
Household_Workers
Other_Workers
Hindus
Muslims
Christians
Sikhs
Buddhists
Jains
Others_Religions
Religion_Not_Stated
LPG_or_PNG_Households
Housholds_with_Electric_Lighting
Households_with_Internet
Households_with_Computer
Households_Rural
Households_Urban
Households
Below_Primary_Education
Primary_Education
Middle_Education
Secondary_Education
Higher_Education
Graduate_Education
Other_Education
Literate_Education
Illiterate_Education
Total_Education
Youth_and_Adult
Middle_Aged
Senior_Citizen
Age_not_stated
Households_with_Bicycle
Households_with_Car_Jeep_Van
Households_with_Radio_Transistor
Households_with_Scooter_Motorcycle_Moped
Households_with_Telephone_Mobile_Phone_Landline_only
Households_with_Telephone_Mobile_Phone_Mobile_only
Households_with_Television
Households_with_Telephone_Mobile_Phone
Households_with_Telephone_Mobile_Phone_Both
Condition_of_occupied_census_houses_Dilapidated_Households
Households_with_separate_kitchen_Cooking_inside_house
Having_bathing_facility_Total_Households
Having_latrine_facility_within_the_premises_Total_Households
Ownership_Owned_Households
Ownership_Rented_Households
Type_of_bathing_facility_Enclosure_without_roof_Households
Type_of_fuel_used_for_cooking_Any_other_Households
Type_of_latrine_facility_Pit_latrine_Households
Type_of_latrine_facility_Other_latrine_Households
Not_having_bathing_facility_within_the_premises_Total_Households
Main_source_of_drinking_water_Un_covered_well_Households
Main_source_of_drinking_water_Spring_Households
Main_source_of_drinking_water_River_Canal_Households
Main_source_of_drinking_water_Other_sources_Households
Location_of_drinking_water_source_Near_the_premises_Households
Location_of_drinking_water_source_Within_the_premises_Households
Main_source_of_drinking_water_Tank_Pond_Lake_Households
Main_source_of_drinking_water_Tapwater_Households
Main_source_of_drinking_water_Tubewell_Borehole_Households
Household_size_1_person_Households
Household_size_2_persons_Households
Household_size_1_to_2_persons
Household_size_3_persons_Households
Household_size_3_to_5_persons_Households
Household_size_4_persons_Households
Household_size_5_persons_Households
Household_size_6_8_persons_Households
Household_size_9_persons_and_above_Households
Location_of_drinking_water_source_Away_Households
Married_couples_1_Households
Married_couples_2_Households
Married_couples_3_Households
Married_couples_3_or_more_Households
Married_couples_4_Households
Married_couples_5__Households
Married_couples_None_Households
Power_Parity_Less_than_Rs_45000
Power_Parity_Rs_45000_90000
Power_Parity_Rs_90000_150000
Power_Parity_Rs_45000_150000
Power_Parity_Rs_150000_240000
Power_Parity_Rs_240000_330000
Power_Parity_Rs_150000_330000
Power_Parity_Rs_330000_425000
Power_Parity_Rs_425000_545000
Power_Parity_Rs_330000_545000
Power_Parity_Above_Rs_545000
Total_Power_Parity
District_code
Households_TV_Computer_Laptop_Telephone_mobile_phone_Scooter_Car
Type_of_latrine_facility_Night_soil_disposed_into_open_drain
Type_of_latrine_Flush_pour_connected_to_other_system_Households
Not_having_latrine_within_premises_Other_source_Open_Households
Source_of_drinking_water_Handpump_Tubewell_Borewell_Households
Drinking_water_Spring_River_Canal_Tank_Pond_Lake_Other_Household
state_UT

Task 6: Database connection and data upload

In [2]:
!pip  install pymysql

Collecting pymysql
  Downloading PyMySQL-1.1.1-py3-none-any.whl (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 kB 635.7 kB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.1

In [3]:
!pip  install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-8.4.0-cp310-cp310-manylinux_2_17_x86_64.whl (19.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.4/19.4 MB 38.6 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-8.4.0

In [ ]:
import mysql.connector

mydb = mysql.connector.connect(
    host="localhost",
    user="root",
    password="",)

print(mydb)
mycursor = mydb.cursor(buffered=True)